eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    prefer-ip-address: true
    
server:
  port: 8761
  
spring:
  application:
    name: zinu-electronics-eureka-server